import { useState, useEffect, useCallback } from 'react';
import { useAnalysis } from '../../context/AnalysisContext';
import { API_URL } from '../../constants';
import { Card } from '../ui';

/**
 * 👶 Business Model Tab — "explicado como a un niño"
 *
 * Shows a simple, Buffett-style explanation of how the company makes money,
 * generated by Claude Haiku. Cached in D1 for 30 days (business model
 * doesn't change often). User can regenerate anytime.
 *
 * Endpoints:
 *   GET  /api/company/:ticker/business-model          → cached content
 *   POST /api/company/:ticker/business-model/generate → new Haiku generation
 */
export default function BusinessModelTab() {
  const { cfg } = useAnalysis();
  const ticker = (cfg?.ticker || '').toUpperCase();

  // TDZ-safe: state before effects
  const [content, setContent] = useState(null);
  const [generatedAt, setGeneratedAt] = useState(null);
  const [stale, setStale] = useState(false);
  const [loading, setLoading] = useState(false);
  const [generating, setGenerating] = useState(false);
  const [error, setError] = useState(null);

  const fetchCached = useCallback(async () => {
    if (!ticker) return;
    setLoading(true);
    setError(null);
    try {
      const r = await fetch(`${API_URL}/api/company/${encodeURIComponent(ticker)}/business-model`);
      const d = await r.json();
      if (d.cached) {
        setContent(d.content);
        setGeneratedAt(d.generated_at);
        setStale(!!d.stale);
      } else {
        setContent(null);
        setGeneratedAt(null);
        setStale(false);
      }
    } catch (e) {
      setError(`Error cargando: ${e.message}`);
    }
    setLoading(false);
  }, [ticker]);

  useEffect(() => { fetchCached(); }, [fetchCached]);

  const generate = async () => {
    setGenerating(true);
    setError(null);
    try {
      const r = await fetch(`${API_URL}/api/company/${encodeURIComponent(ticker)}/business-model/generate`, {
        method: 'POST',
      });
      const d = await r.json();
      if (d.error) {
        setError(d.error);
      } else {
        setContent(d.content);
        setGeneratedAt(d.generated_at);
        setStale(false);
      }
    } catch (e) {
      setError(`Error generando: ${e.message}`);
    }
    setGenerating(false);
  };

  if (!ticker) {
    return (
      <div style={{textAlign: 'center', padding: '60px 20px', color: 'var(--text-tertiary)'}}>
        Selecciona una posición del Portfolio para ver su modelo de negocio.
      </div>
    );
  }

  const ageLabel = (() => {
    if (!generatedAt) return null;
    const ageMs = Date.now() - new Date(generatedAt).getTime();
    const d = Math.round(ageMs / 86400000);
    if (d === 0) return 'generado hoy';
    if (d === 1) return 'hace 1 día';
    if (d < 30) return `hace ${d} días`;
    return `hace ${Math.round(d / 30)} meses`;
  })();

  return (
    <div>
      {/* Header */}
      <div style={{display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 20, gap: 16, flexWrap: 'wrap'}}>
        <div>
          <h2 style={{margin: '0 0 4px', fontSize: 20, fontWeight: 700, color: 'var(--text-primary)', fontFamily: 'var(--fd)'}}>
            👶 Cómo gana dinero — {cfg?.name || ticker}
          </h2>
          <p style={{margin: 0, fontSize: 11, color: 'var(--text-tertiary)'}}>
            Explicación simple estilo Warren Buffett para que cualquiera entienda el negocio.
            {ageLabel && <span> {ageLabel}{stale ? ' · ⚠️ desactualizado, regenera' : ''}.</span>}
          </p>
        </div>
        <button onClick={generate} disabled={generating}
          title="Genera con Claude Haiku (~$0.002)"
          style={{padding: '8px 14px', borderRadius: 8, border: '1px solid var(--gold)', background: 'var(--gold-dim)', color: 'var(--gold)', fontSize: 11, fontWeight: 700, cursor: generating ? 'wait' : 'pointer', fontFamily: 'var(--fm)', whiteSpace: 'nowrap'}}>
          {generating ? '🧠 Generando...' : content ? '🔄 Regenerar' : '✨ Generar explicación'}
        </button>
      </div>

      {error && (
        <div style={{padding: 12, background: 'rgba(248,113,113,.1)', border: '1px solid rgba(248,113,113,.3)', borderRadius: 8, color: 'var(--red)', fontSize: 12, marginBottom: 16, fontFamily: 'var(--fm)'}}>
          ⚠️ {error}
        </div>
      )}

      {loading && !content && (
        <div style={{textAlign: 'center', padding: 40, color: 'var(--text-tertiary)', fontFamily: 'var(--fm)', fontSize: 12}}>
          Cargando explicación...
        </div>
      )}

      {!loading && !content && (
        <Card style={{padding: 30, textAlign: 'center'}}>
          <div style={{fontSize: 42, marginBottom: 14}}>👶</div>
          <div style={{fontSize: 15, color: 'var(--text-secondary)', marginBottom: 8, fontFamily: 'var(--fd)', fontWeight: 700}}>
            Sin explicación generada todavía
          </div>
          <div style={{fontSize: 11, color: 'var(--text-tertiary)', lineHeight: 1.7, maxWidth: 520, margin: '0 auto'}}>
            Pulsa <strong>✨ Generar explicación</strong> y Claude te explicará este negocio
            como si se lo contase a un niño de 8 años. Con analogías simples, sin jerga,
            y los 2-3 productos clave que generan casi todo el dinero.
            Se cachea 30 días (barato como 2¢).
          </div>
        </Card>
      )}

      {content && (
        <Card style={{padding: 24}}>
          <MarkdownLite content={content} />
        </Card>
      )}
    </div>
  );
}

// Same lightweight markdown renderer as TranscriptTab (duplicated to avoid
// coupling; if both files grow it's worth extracting to a shared utility).
function MarkdownLite({ content }) {
  if (!content) return null;
  const lines = content.split('\n');
  const out = [];
  let listBuf = [];
  const flushList = () => {
    if (listBuf.length) {
      out.push(
        <ol key={`ol-${out.length}`} style={{margin: '4px 0 12px 18px', paddingLeft: 4, lineHeight: 1.9}}>
          {listBuf.map((li, i) => (
            <li key={i} style={{fontSize: 13, color: 'var(--text-secondary)', marginBottom: 4}}>
              <InlineMd text={li} />
            </li>
          ))}
        </ol>
      );
      listBuf = [];
    }
  };
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    const trimmed = line.trim();
    if (trimmed.startsWith('## ')) {
      flushList();
      out.push(<h3 key={`h-${i}`} style={{margin: '18px 0 6px', fontSize: 14, fontWeight: 700, color: 'var(--gold)', fontFamily: 'var(--fd)'}}>{trimmed.slice(3)}</h3>);
    } else if (trimmed.startsWith('# ')) {
      flushList();
      out.push(<h2 key={`h-${i}`} style={{margin: '20px 0 8px', fontSize: 18, fontWeight: 800, color: 'var(--text-primary)', fontFamily: 'var(--fd)'}}>{trimmed.slice(2)}</h2>);
    } else if (trimmed.startsWith('- ') || trimmed.startsWith('* ')) {
      listBuf.push(trimmed.slice(2));
    } else if (/^\d+\.\s/.test(trimmed)) {
      listBuf.push(trimmed.replace(/^\d+\.\s/, ''));
    } else if (trimmed) {
      flushList();
      out.push(<p key={`p-${i}`} style={{margin: '8px 0', fontSize: 13, color: 'var(--text-secondary)', lineHeight: 1.9}}><InlineMd text={trimmed} /></p>);
    }
  }
  flushList();
  return <div>{out}</div>;
}

function InlineMd({ text }) {
  const parts = [];
  let remaining = text;
  let key = 0;
  while (remaining.length > 0) {
    const bold = remaining.match(/\*\*([^*]+)\*\*/);
    if (bold && bold.index === 0) {
      parts.push(<strong key={key++} style={{color: 'var(--text-primary)'}}>{bold[1]}</strong>);
      remaining = remaining.slice(bold[0].length);
    } else if (bold) {
      parts.push(<span key={key++}>{remaining.slice(0, bold.index)}</span>);
      remaining = remaining.slice(bold.index);
    } else {
      parts.push(<span key={key++}>{remaining}</span>);
      remaining = '';
    }
  }
  return <>{parts}</>;
}
